//! The full libretro-database `cht` collection for SNES (CC BY-SA 4.0 — see
//! `THIRD-PARTY-NOTICES.md`), embedded so the app needs no network at
//! runtime and works from a clean install with zero setup (plan §4.4,
//! revision). Only the *codes* come from there — an address/value pair is a
//! fact, not a creative work; every description is the database's own,
//! reproduced verbatim (they're plain factual labels, not prose).
//!
//! `cheats_data.txt` (checked in next to this file, generated by
//! `scripts/gen_cheats_data.py` from
//! <https://github.com/libretro/libretro-database>'s
//! `cht/Nintendo - Super Nintendo Entertainment System/` folder — rerun
//! that script and re-commit the file to pick up upstream's own updates)
//! is one block per `.cht` file, its own display name — e.g.
//! `"Aladdin (USA)"`, matching that ecosystem's usual
//! `Title (Region) (Flags)` naming — as a `G` line, its cheats as
//! `C\t<description>\t<code>` lines right after:
//!
//! ```text
//! G\tAladdin (USA)
//! C\tInfinite Apples\t7E036999
//! C\tMax Gems\t7E036B99
//! ```
//!
//! Two kinds of cheat are left out at generation time:
//! - one that needs a value the player would have to pick (the source
//!   marks these with a literal `X`/`?` placeholder byte in the code, e.g.
//!   `"7FC136XX"`) — there's no field in this app's simple on/off toggle
//!   for that, so shipping one would just be a checkbox that silently
//!   does nothing;
//! - one whose code is implausibly long (over 96 characters — a real one
//!   found during development, "poke every byte in a table" encoded as a
//!   single 602-char, 67-address combo, crashed this app's snes9x-libretro
//!   core build outright: a stack-buffer overflow in `retro_cheat_set`.
//!   `for_title`'s own test suite has a regression test pinning this).
//!
//! Matched by the ROM's own title (plan revision — used to be the SNES
//! cartridge header's internal title, which only a small hand-picked slice
//! of games had a curated entry for here; this app has no way to read
//! 2000+ games' headers without owning every cartridge, so there's no way
//! to key a comprehensive database by that fact). A caller passes whatever
//! title it already has for display (`xperience_app::runner` passes the
//! ROM file's stem, the same string saves/notes are already keyed by) —
//! exact match first (case-insensitive), so a ROM named the usual
//! `Title (Region)` way gets exactly that region's addresses; if that
//! finds nothing, a looser match ignoring every trailing `(...)` group on
//! both sides (region, revision, "Action Replay"/"Game Genie" tags — a
//! ROM stripped down to just its own name) picks whichever matching entry
//! has the most cheats — not just the first one found, a real bug caught
//! in testing (a 29-cheat "(Action Replay)" file for the same game sorted
//! ahead of its own 2400-cheat plain release). A cartridge whose codes
//! don't apply to the player's actual dump just doesn't do anything when
//! toggled — same as a mismatched cheat always has, nothing to validate
//! against.

use std::sync::OnceLock;

/// One cheat: a description and the code string passed straight through to
/// the core's `retro_cheat_set` (raw hex, Game Genie or Pro Action Replay —
/// whatever format the database shipped it in). Both borrow straight from
/// the embedded data file — no per-lookup allocation.
pub struct CheatDef {
    pub desc: &'static str,
    pub code: &'static str,
}

const DATA: &str = include_str!("cheats_data.txt");

/// `(game name, its cheat lines as raw "C\t..." text)` pairs, in file order.
/// Built once, the first time any lookup happens — a single linear pass
/// over ~2.7 MB of embedded text, not something worth redoing per call.
fn index() -> &'static [(&'static str, &'static str)] {
    static INDEX: OnceLock<Vec<(&'static str, &'static str)>> = OnceLock::new();
    INDEX.get_or_init(|| {
        let mut out = Vec::new();
        let mut cur: Option<&'static str> = None;
        let mut block_start = 0usize;
        let mut offset = 0usize;
        for line in DATA.split_inclusive('\n') {
            if let Some(name) = line.strip_prefix("G\t").and_then(|s| s.strip_suffix('\n')) {
                if let Some(prev) = cur.replace(name) {
                    out.push((prev, &DATA[block_start..offset]));
                }
                block_start = offset + line.len();
            }
            offset += line.len();
        }
        if let Some(prev) = cur {
            out.push((prev, &DATA[block_start..offset]));
        }
        out
    })
}

/// Strip every trailing ` (...)` group (region, revision, dump-tool tag,
/// …) and lowercase what's left — `"Aladdin (Europe) (Rev 1)"` and
/// `"aladdin.sfc"`'s stem `"Aladdin"` both reduce to `"aladdin"`.
fn base_name(name: &str) -> String {
    let mut s = name.trim();
    loop {
        let t = s.trim_end();
        if t.ends_with(')') {
            if let Some(open) = t.rfind('(') {
                s = t[..open].trim_end();
                continue;
            }
        }
        break;
    }
    s.to_ascii_lowercase()
}

fn parse_block(block: &'static str) -> Vec<CheatDef> {
    block
        .lines()
        .filter_map(|line| {
            let rest = line.strip_prefix("C\t")?;
            let (desc, code) = rest.split_once('\t')?;
            Some(CheatDef { desc, code })
        })
        .collect()
}

/// Cheats for a ROM's `title` (see this module's doc comment for how the
/// match works), or empty if nothing in the database lines up with it.
pub fn for_title(title: &str) -> Vec<CheatDef> {
    let query = title.trim();
    if query.is_empty() {
        return Vec::new();
    }
    if let Some(&(_, block)) = index()
        .iter()
        .find(|(name, _)| name.eq_ignore_ascii_case(query))
    {
        return parse_block(block);
    }
    // Loose fallback: several files can share a base name (regions, or an
    // alternate-format dump like "(Action Replay)" sitting right next to
    // the plain release) — picking whichever sorts first was a real bug
    // caught in testing, e.g. a 29-cheat "(Action Replay)" variant beating
    // out its own game's 2400-cheat plain release purely by file-name
    // alphabetical accident. Picking the one with the most cheats instead
    // has no such trap: it's the most complete list for the game either
    // way, whichever file it happens to live in.
    let query_base = base_name(query);
    if query_base.is_empty() {
        return Vec::new();
    }
    index()
        .iter()
        .filter(|(name, _)| base_name(name) == query_base)
        .max_by_key(|(_, block)| block.bytes().filter(|&b| b == b'\n').count())
        .map(|&(_, block)| parse_block(block))
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn matches_exact_title_case_insensitively() {
        let cheats = for_title("aladdin (usa)");
        assert!(!cheats.is_empty());
        assert!(cheats.iter().any(|c| c.desc == "Infinite Apples"));
    }

    #[test]
    fn falls_back_to_base_name_ignoring_region_tags() {
        // No file is named exactly "Aladdin" — only "Aladdin (USA)" and
        // friends — so this only succeeds via the base-name fallback.
        let cheats = for_title("Aladdin");
        assert!(!cheats.is_empty());
    }

    #[test]
    fn unknown_title_returns_empty() {
        assert!(for_title("Not A Real Game Title At All 12345").is_empty());
    }

    #[test]
    fn no_cheat_code_carries_a_placeholder_byte() {
        // The generation script (see this module's doc comment) should have
        // dropped every code needing a player-picked value.
        for (_, block) in index() {
            for c in parse_block(block) {
                assert!(
                    !c.code.contains(['X', 'x', '?']),
                    "{:?} still has a placeholder code {:?}",
                    c.desc,
                    c.code
                );
            }
        }
    }

    #[test]
    fn no_cheat_code_is_long_enough_to_crash_the_core() {
        // A real, reproduced bug: the snes9x-libretro core build this app
        // ships has a stack-buffer overflow in retro_cheat_set on a long
        // enough multi-address code (confirmed SIGABRT/__stack_chk_fail at
        // 602 chars, 67 "+"-joined addresses, from one of this database's
        // more extreme "poke every byte in a table" entries). 128 is a
        // generous margin under that; this guards a future regeneration of
        // cheats_data.txt from silently reintroducing the crash.
        const MAX_SAFE_LEN: usize = 128;
        for (_, block) in index() {
            for c in parse_block(block) {
                assert!(
                    c.code.len() <= MAX_SAFE_LEN,
                    "{:?} has a {}-char code, past the {MAX_SAFE_LEN}-char safety cap",
                    c.desc,
                    c.code.len()
                );
            }
        }
    }
}
